### ISSUE TITLE
Feature Suggestion: Hide number of modules

### ISSUE THREAD

**Issue by GhostwheelX** [zarmstrong/fvtt-hide-buttons#2]
Might you be able to add by any chance the ability to hide from players the number of modules that are active in the game? 

Much appreciated 😄

**Comment by zarmstrong** [comment]
Done -- try version 1.1.0

**Comment by GhostwheelX** [comment]
Just updated to 1.1.0, but it's still showing the number for players for some reason...
![image](https://user-images.githubusercontent.com/68725723/125861458-0bb36a87-e82e-4ac6-b9fe-8bd72a3bab0b.png)
EDIT: That's as a player.

**Comment by zarmstrong** [comment]
hmm, ok I will mess with it and see if I can reproduce

**Comment by GhostwheelX** [comment]
Should this issue be re-opened in that case? Not sure how to do it myself.

**Comment by zarmstrong** [comment]
I changed the filename and forgot to update the module.json to point to the new file name.

Should be fixed in 1.1.2
